from django.urls import path
from . import views
from .views import registrar_pedido, ver_pedidos, webpay_callback, registrar_usuario, stripe_checkout

from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('acabados/', views.acabados, name='acabados'),
    path('accesorios_varios/', views.accesorios_varios, name='accesorios_varios'),
    path('arena/', views.arena, name='arena'),
    path('barnices/', views.barnices, name='barnices'),
    path('cascos/', views.cascos, name='cascos'),
    path('cemento/', views.cemento, name='cemento'),
    path('ceramicos/', views.ceramicos, name='ceramicos'),
    path('destornilladores/', views.destornilladores, name='destornilladores'),
    path('equipos_medicion/', views.equipos_medicion, name='equipos_medicion'),
    path('equipos_seguridad/', views.equipos_seguridad, name='equipos_seguridad'),
    path('fijaciones_adhesivos/', views.fijaciones_adhesivos, name='fijaciones_adhesivos'),
    path('guantes/', views.guantes, name='guantes'),
    path('herramientas_electricas/', views.herramientas_electricas, name='herramientas_electricas'),
    path('herramientas_manuales/', views.herramientas_manuales, name='herramientas_manuales'),
    path('iniciar_sesion/', views.iniciar_sesion, name='iniciar_sesion'),
    path('ladrillos/', views.ladrillos, name='ladrillos'),
    path('lentes_seguridad/', views.lentes_seguridad, name='lentes_seguridad'),
    path('lijadoras/', views.lijadoras, name='lijadoras'),
    path('llaves/', views.llaves, name='llaves'),
    path('martillos/', views.martillos, name='martillos'),
    path('materiales_basicos/', views.materiales_basicos, name='materiales_basicos'),
    path('materiales_construccion/', views.materiales_construccion, name='materiales_construccion'),
    path('pinturas/', views.pinturas, name='pinturas'),
    path('registrate/', views.registrate, name='registrate'),
    path('sierras/', views.sierras, name='sierras'),
    path('taladros/', views.taladros, name='taladros'),
    path('tornillos_anchajes/', views.tornillos_anchajes, name='tornillos_anchajes'),
    path('base/', views.base, name='base'),
    path('crud/', views.crud, name='crud'),
    path('resultados/', views.resultados_busqueda, name='resultados_busqueda'),
    path('registrar-pedido/', registrar_pedido, name='registrar_pedido'),
    path('ver-pedidos/', views.ver_pedidos, name='ver_pedidos'),
    path('carrito/', views.carrito, name='carrito'),
    path('pago_exitoso/', views.pago_exitoso, name='pago_exitoso'),
    path('webpay/callback', webpay_callback, name='webpay_callback'),
    path('logout/', LogoutView.as_view(next_page='inicio'), name='logout'),
    path('cerrar_sesion/', views.cerrar_sesion, name='cerrar_sesion'),
    path('usuarios/crud/', views.crud_usuarios, name='crud_usuarios'),
    path('usuarios/crear/', views.usuario_crear, name='usuario_crear'),
    path('usuarios/editar/<uuid:usuario_id>/', views.usuario_editar, name='usuario_editar'),
    path('usuarios/eliminar/<uuid:usuario_id>/', views.usuario_eliminar, name='usuario_eliminar'),
    path('pagos/', views.pagos, name='pagos'),
    path('compras/', views.compras, name='compras'),
    path('sincronizar_sesion/', views.sincronizar_sesion, name='sincronizar_sesion'),  # <-- Agrega esta línea
    path('busqueda/', views.resultados_busqueda, name='resultados_busqueda'),
    path('pedidos/', views.lista_pedidos, name='lista_pedidos'),
    path('aprobar_pedido/<int:pedido_id>/', views.aprobar_pedido, name='aprobar_pedido'),
    path('rechazar_pedido/<int:pedido_id>/', views.rechazar_pedido, name='rechazar_pedido'),
    path('pago_erroneo/', views.pago_erroneo, name='pago_erroneo'),

    path('confirmar_pago/<int:pedido_id>/', views.confirmar_pago, name='confirmar_pago'),
    path('registrar_entrega/<int:pedido_id>/', views.registrar_entrega, name='registrar_entrega'),
    path('en_construccion/', views.en_construccion, name='en_construccion'),
    path('preparar_pedido/<int:pedido_id>/', views.preparar_pedido, name='preparar_pedido'),
    path('entregar_a_vendedor/<int:pedido_id>/', views.entregar_a_vendedor, name='entregar_a_vendedor'),
    path('stripe_checkout/', stripe_checkout, name='stripe_checkout'),
]