# Generated by Django 5.0.6 on 2025-06-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal_origen', models.CharField(max_length=100)),
                ('sucursal_destino', models.CharField(max_length=100)),
                ('productos', models.JSONField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
